### ISSUE TITLE
dev20220309: AWD value displayed instead of AWA

### ISSUE THREAD

**Issue by W-Geronius** [norbert-walter/esp32-nmea2000-obp60#22]
The windsensor transmits this Apparent Winddirection:
![image](https://user-images.githubusercontent.com/18160302/157433869-f0e73e93-e5bf-42b1-92bd-55de133fa50d.png)

Webinterface (DATA) of esp correctly displays
![image](https://user-images.githubusercontent.com/18160302/157433586-47bfd466-0632-41ed-8d2b-8f79c5ae103a.png)

On OBP60 AWA displays as 244 deg in all (one, two, values) formats. 
This is wrong, should be same as above (-116°)

**Comment by norbert-walter** [comment]
The value for apparant wind is correct for now. Only the representation differs in the advertisements. It is not exactly defined how apparant wind should be displayed, as 0...360° or as +/-180°.

**Comment by W-Geronius** [comment]
it's not explicitly defined anywhere that's correct, the majority of commercial products however display 180° +,- or P,S. So it appears to be a convention. In fact I am am not aware any brand displaying 0..360° for AWA.
AWD certainly get's displayed as 0...360° as it is a direction relative to true North

**Comment by norbert-walter** [comment]
The problem is the treatment in the formatter. It gets rad as any angular value and converts that to deg. A case distinction would then have to be inserted in the formatter for AWA. However, the formatter does not know what the value is. He only knows that these are angular values. The software design is inadequate at this point. Actually, the numerical value of AWA is not of interest. A pointer instrument has the better informative value.

**Comment by norbert-walter** [comment]
I close it.
